# -*- coding: utf-8 -*-
"""OCR to Extract Value.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DUKN7wLT_CCN8uvWoWLweLNgzhBYT8ju
"""

!sudo apt install tesseract-ocr
!pip install pytesseract

pip install --ignore-installed Pillow==9.0.0

from google.colab import files
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
import pytesseract
from pytesseract import Output
import cv2

uploaded = files.upload()

path = "/content/34.jpg"

#https://stackoverflow.com/questions/32302180/typeerror-image-data-can-not-convert-to-float
image = cv2.imread(path)
plt.imshow(image)

image2 = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
plt.imshow(image2)

ret,thresh3 = cv2.threshold(image2,127,255,cv2.THRESH_TRUNC)

data = pytesseract.image_to_data(thresh3, output_type='data.frame')
data

data[['conf','text']]

for i in range(len(data)):
  if data["conf"][i] == -1:
    print(data['text'][i])

data.conf.unique()

for box in range(len(data)):
  if data["conf"][box] >= 0:
    image = cv2.rectangle(image, (data['left'][box], data['top'][box]), 
                          (data['left'][box]+data['width'][box], data['top'][box]+data['height'][box]), 
                          (0,255,0),2)

plt.imshow(image)

result = pytesseract.image_to_string(thresh3)
print(result)

